name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      packages: write

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@master
        with:
          node-version: '22.x'
      - name: Corepack
        run: corepack enable
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build

      - uses: actions/setup-node@master
        with:
          always-auth: true
          registry-url: 'https://npm.pkg.github.com'
          scope: '@2ltech'
      - name: Publish Github
        continue-on-error: true
        run: yarn npm publish --access=public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YARN_NPM_PUBLISH_REGISTRY: 'https://npm.pkg.github.com'

      - uses: actions/setup-node@master
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@2ltech'
      - name: Publish NPM
        run: yarn npm publish --access=public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
